const MULTIPLIERS = [
    // Image base size 48x48 px

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CURSORS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //
    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 48 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 96 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 624 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 672 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 720 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 768 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 816 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 864 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 912 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 1344 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 1444 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 1492 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 1636 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 1732 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- GRANDMAS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Farmer grandmas",
        imagePos: { x: 48, y: 0 },
        category: "grandma",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Miner grandmas",
        imagePos: { x: 48, y: 48 },
        category: "grandma",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 48, y: 96 },
        category: "grandma",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 48, y: 624 },
        category: "grandma",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 48, y: 672 },
        category: "grandma",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 48, y: 720 },
        category: "grandma",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 48, y: 768 },
        category: "grandma",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 48, y: 816 },
        category: "grandma",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 48, y: 864 },
        category: "grandma",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 48, y: 912 },
        category: "grandma",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 48, y: 1344 },
        category: "grandma",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 48, y: 1444 },
        category: "grandma",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 48, y: 1492 },
        category: "grandma",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 48, y: 1636 },
        category: "grandma",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 48, y: 1732 },
        category: "grandma",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FARMS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 96, y: 0 },
        category: "farm",
        description: "The farms are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 96, y: 48 },
        category: "farm",
        description: "The farms are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 96, y: 96 },
        category: "farm",
        description: "The farms are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 96, y: 624 },
        category: "farm",
        description: "The farms are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 96, y: 672 },
        category: "farm",
        description: "The farms are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 96, y: 720 },
        category: "farm",
        description: "The farms are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 96, y: 768 },
        category: "farm",
        description: "The farms are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 96, y: 816 },
        category: "farm",
        description: "The farms are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 96, y: 864 },
        category: "farm",
        description: "The farms are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 96, y: 912 },
        category: "farm",
        description: "The farms are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 96, y: 1344 },
        category: "farm",
        description: "The farms are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 96, y: 1444 },
        category: "farm",
        description: "The farms are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 96, y: 1492 },
        category: "farm",
        description: "The farms are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 96, y: 1636 },
        category: "farm",
        description: "The farms are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 96, y: 1732 },
        category: "farm",
        description: "The farms are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- MINES ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 144, y: 0 },
        category: "mine",
        description: "The mines are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 144, y: 48 },
        category: "mine",
        description: "The mines are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 144, y: 96 },
        category: "mine",
        description: "The mines are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 144, y: 624 },
        category: "mine",
        description: "The mines are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 144, y: 672 },
        category: "mine",
        description: "The mines are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 144, y: 720 },
        category: "mine",
        description: "The mines are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 144, y: 768 },
        category: "mine",
        description: "The mines are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 144, y: 816 },
        category: "mine",
        description: "The mines are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 144, y: 864 },
        category: "mine",
        description: "The mines are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 144, y: 912 },
        category: "mine",
        description: "The mines are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 144, y: 1344 },
        category: "mine",
        description: "The mines are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 144, y: 1444 },
        category: "mine",
        description: "The mines are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 144, y: 1492 },
        category: "mine",
        description: "The mines are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 144, y: 1636 },
        category: "mine",
        description: "The mines are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 144, y: 1732 },
        category: "mine",
        description: "The mines are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FACTORY ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 192, y: 0 },
        category: "factory",
        description: "The factories are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 192, y: 48 },
        category: "factory",
        description: "The factories are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 192, y: 96 },
        category: "factory",
        description: "The factories are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 192, y: 624 },
        category: "factory",
        description: "The factories are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 192, y: 672 },
        category: "factory",
        description: "The factories are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 192, y: 720 },
        category: "factory",
        description: "The factories are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 192, y: 768 },
        category: "factory",
        description: "The factories are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 192, y: 816 },
        category: "factory",
        description: "The factories are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 192, y: 864 },
        category: "factory",
        description: "The factories are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 192, y: 912 },
        category: "factory",
        description: "The factories are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 192, y: 1344 },
        category: "factory",
        description: "The factories are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 192, y: 1444 },
        category: "factory",
        description: "The factories are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 192, y: 1492 },
        category: "factory",
        description: "The factories are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 192, y: 1636 },
        category: "factory",
        description: "The factories are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 192, y: 1732 },
        category: "factory",
        description: "The factories are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- BANK ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 720, y: 0 },
        category: "bank",
        description: "The banks are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 720, y: 48 },
        category: "bank",
        description: "The banks are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 720, y: 96 },
        category: "bank",
        description: "The banks are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 720, y: 624 },
        category: "bank",
        description: "The banks are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 720, y: 672 },
        category: "bank",
        description: "The banks are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 720, y: 720 },
        category: "bank",
        description: "The banks are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 720, y: 768 },
        category: "bank",
        description: "The banks are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 720, y: 816 },
        category: "bank",
        description: "The banks are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 720, y: 864 },
        category: "bank",
        description: "The banks are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 720, y: 912 },
        category: "bank",
        description: "The banks are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 720, y: 1344 },
        category: "bank",
        description: "The banks are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 720, y: 1444 },
        category: "bank",
        description: "The banks are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 720, y: 1492 },
        category: "bank",
        description: "The banks are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 720, y: 1636 },
        category: "bank",
        description: "The banks are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 720, y: 1732 },
        category: "bank",
        description: "The banks are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- TEMPLE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 768, y: 0 },
        category: "temple",
        description: "The temples are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 768, y: 48 },
        category: "temple",
        description: "The temples are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 768, y: 96 },
        category: "temple",
        description: "The temples are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 768, y: 624 },
        category: "temple",
        description: "The temples are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 768, y: 672 },
        category: "temple",
        description: "The temples are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 768, y: 720 },
        category: "temple",
        description: "The temples are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 768, y: 768 },
        category: "temple",
        description: "The temples are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 768, y: 816 },
        category: "temple",
        description: "The temples are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 768, y: 864 },
        category: "temple",
        description: "The temples are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 768, y: 912 },
        category: "temple",
        description: "The temples are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 768, y: 1344 },
        category: "temple",
        description: "The temples are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 768, y: 1444 },
        category: "temple",
        description: "The temples are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 768, y: 1492 },
        category: "temple",
        description: "The temples are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 768, y: 1636 },
        category: "temple",
        description: "The temples are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 768, y: 1732 },
        category: "temple",
        description: "The temples are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ---------- WIZARD TOWER ----------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 816, y: 0 },
        category: "wizard-tower",
        description: "The wizard towers are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 816, y: 48 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 816, y: 96 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 816, y: 624 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 816, y: 672 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 816, y: 720 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 816, y: 768 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 816, y: 816 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 816, y: 864 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 816, y: 912 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 816, y: 1344 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 816, y: 1444 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 816, y: 1492 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 816, y: 1636 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 816, y: 1732 },
        category: "wizard-tower",
        description: "The wizard towers are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- SHIPMENT ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 240, y: 0 },
        category: "shipment",
        description: "The shipments are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 240, y: 48 },
        category: "shipment",
        description: "The shipments are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 240, y: 96 },
        category: "shipment",
        description: "The shipments are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 240, y: 624 },
        category: "shipment",
        description: "The shipments are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 240, y: 672 },
        category: "shipment",
        description: "The shipments are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 240, y: 720 },
        category: "shipment",
        description: "The shipments are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 240, y: 768 },
        category: "shipment",
        description: "The shipments are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 240, y: 816 },
        category: "shipment",
        description: "The shipments are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 240, y: 864 },
        category: "shipment",
        description: "The shipments are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 240, y: 912 },
        category: "shipment",
        description: "The shipments are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 240, y: 1344 },
        category: "shipment",
        description: "The shipments are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 240, y: 1444 },
        category: "shipment",
        description: "The shipments are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 240, y: 1492 },
        category: "shipment",
        description: "The shipments are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 240, y: 1636 },
        category: "shipment",
        description: "The shipments are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 240, y: 1732 },
        category: "shipment",
        description: "The shipments are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ----------- ALCHEMY LAB ----------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 288, y: 0 },
        category: "alchemy-lab",
        description: "The alchemy labs are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 288, y: 48 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 288, y: 96 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 288, y: 624 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 288, y: 672 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 288, y: 720 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 288, y: 768 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 288, y: 816 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 288, y: 864 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 288, y: 912 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 288, y: 1344 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 288, y: 1444 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 288, y: 1492 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 288, y: 1636 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 288, y: 1732 },
        category: "alchemy-lab",
        description: "The alchemy labs are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- PORTAL ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 336, y: 0 },
        category: "portal",
        description: "The portals are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 336, y: 48 },
        category: "portal",
        description: "The portals are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 336, y: 96 },
        category: "portal",
        description: "The portals are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 336, y: 624 },
        category: "portal",
        description: "The portals are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 336, y: 672 },
        category: "portal",
        description: "The portals are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 336, y: 720 },
        category: "portal",
        description: "The portals are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 336, y: 768 },
        category: "portal",
        description: "The portals are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 336, y: 816 },
        category: "portal",
        description: "The portals are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 336, y: 864 },
        category: "portal",
        description: "The portals are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 336, y: 912 },
        category: "portal",
        description: "The portals are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 336, y: 1344 },
        category: "portal",
        description: "The portals are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 336, y: 1444 },
        category: "portal",
        description: "The portals are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 336, y: 1492 },
        category: "portal",
        description: "The portals are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 336, y: 1636 },
        category: "portal",
        description: "The portals are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 336, y: 1732 },
        category: "portal",
        description: "The portals are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- TIME MACHINE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 384, y: 0 },
        category: "time-machine",
        description: "The time machines are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 384, y: 48 },
        category: "time-machine",
        description: "The time machines are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 384, y: 96 },
        category: "time-machine",
        description: "The time machines are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 384, y: 624 },
        category: "time-machine",
        description: "The time machines are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 384, y: 672 },
        category: "time-machine",
        description: "The time machines are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 384, y: 720 },
        category: "time-machine",
        description: "The time machines are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 384, y: 768 },
        category: "time-machine",
        description: "The time machines are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 384, y: 816 },
        category: "time-machine",
        description: "The time machines are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 384, y: 864 },
        category: "time-machine",
        description: "The time machines are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 384, y: 912 },
        category: "time-machine",
        description: "The time machines are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 384, y: 1344 },
        category: "time-machine",
        description: "The time machines are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 384, y: 1444 },
        category: "time-machine",
        description: "The time machines are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 384, y: 1492 },
        category: "time-machine",
        description: "The time machines are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 384, y: 1636 },
        category: "time-machine",
        description: "The time machines are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 384, y: 1732 },
        category: "time-machine",
        description: "The time machines are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- ANTIMATTER CONDENSER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 624, y: 0 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 624, y: 48 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 624, y: 96 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 624, y: 624 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 624, y: 672 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 624, y: 720 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 624, y: 768 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 624, y: 816 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 624, y: 864 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 624, y: 912 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 624, y: 1344 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 624, y: 1444 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 624, y: 1492 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 624, y: 1636 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 624, y: 1732 },
        category: "antimatter-condenser",
        description: "The antimatter condensers are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- PRISM ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 672, y: 0 },
        category: "prism",
        description: "The prisms are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 672, y: 48 },
        category: "prism",
        description: "The prisms are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 672, y: 96 },
        category: "prism",
        description: "The prisms are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 672, y: 624 },
        category: "prism",
        description: "The prisms are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 672, y: 672 },
        category: "prism",
        description: "The prisms are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 672, y: 720 },
        category: "prism",
        description: "The prisms are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 672, y: 768 },
        category: "prism",
        description: "The prisms are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 672, y: 816 },
        category: "prism",
        description: "The prisms are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 672, y: 864 },
        category: "prism",
        description: "The prisms are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 672, y: 912 },
        category: "prism",
        description: "The prisms are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 672, y: 1344 },
        category: "prism",
        description: "The prisms are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 672, y: 1444 },
        category: "prism",
        description: "The prisms are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 672, y: 1492 },
        category: "prism",
        description: "The prisms are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 672, y: 16360 },
        category: "prism",
        description: "The prisms are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 672, y: 17320 },
        category: "prism",
        description: "The prisms are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CHANCMAKER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 912, y: 0 },
        category: "chancemaker",
        description: "The chancemakers are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 912, y: 48 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 912, y: 96 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 912, y: 624 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 912, y: 672 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 912, y: 720 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 912, y: 768 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 912, y: 816 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 912, y: 864 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 912, y: 912 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 912, y: 1344 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 912, y: 1444 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 912, y: 1492 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 912, y: 1636 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 912, y: 1732 },
        category: "chancemaker",
        description: "The chancemakers are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FRACTAL ENGINE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 960, y: 0 },
        category: "fractal-engine",
        description: "The fractal engines are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 960, y: 48 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 960, y: 96 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 960, y: 624 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 960, y: 672 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 960, y: 720 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 960, y: 768 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 960, y: 816 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 960, y: 864 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 960, y: 912 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 960, y: 1344 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 960, y: 1444 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 960, y: 1492 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 960, y: 1636 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 960, y: 1732 },
        category: "fractal-engine",
        description: "The fractal engines are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- JAVASCRIPT CONSOLE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 1536, y: 0 },
        category: "javascript-console",
        description: "The javascript consoles are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 1536, y: 48 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 1536, y: 96 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 1536, y: 624 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 1536, y: 672 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 1536, y: 720 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 1536, y: 768 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 1536, y: 816 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 1536, y: 864 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 1536, y: 912 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 1536, y: 1344 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 1536, y: 1444 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 1536, y: 1492 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 1536, y: 1636 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 1536, y: 1732 },
        category: "javascript-console",
        description: "The javascript consoles are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- IDLEVERSE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 1584, y: 0 },
        category: "idleverse",
        description: "The idleverses are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 1584, y: 48 },
        category: "idleverse",
        description: "The idleverses are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 1584, y: 96 },
        category: "idleverse",
        description: "The idleverses are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 1584, y: 624 },
        category: "idleverse",
        description: "The idleverses are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 1584, y: 672 },
        category: "idleverse",
        description: "The idleverses are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 1584, y: 720 },
        category: "idleverse",
        description: "The idleverses are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 1584, y: 768 },
        category: "idleverse",
        description: "The idleverses are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 1584, y: 816 },
        category: "idleverse",
        description: "The idleverses are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 1584, y: 864 },
        category: "idleverse",
        description: "The idleverses are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 1584, y: 912 },
        category: "idleverse",
        description: "The idleverses are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 1584, y: 1344 },
        category: "idleverse",
        description: "The idleverses are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 1584, y: 1444 },
        category: "idleverse",
        description: "The idleverses are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 1584, y: 1492 },
        category: "idleverse",
        description: "The idleverses are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 1584, y: 1636 },
        category: "idleverse",
        description: "The idleverses are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 1584, y: 1732 },
        category: "idleverse",
        description: "The idleverses are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CORTEX BAKER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 1632, y: 0 },
        category: "cortex-baker",
        description: "The cortex bakers are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 1632, y: 48 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 1632, y: 96 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 1632, y: 624 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 1632, y: 672 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 1632, y: 720 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 1632, y: 768 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 1632, y: 816 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 1632, y: 864 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 1632, y: 912 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 1632, y: 1344 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 1632, y: 1444 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 1632, y: 1492 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 1632, y: 1636 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 1632, y: 1732 },
        category: "cortex-baker",
        description: "The cortex bakers are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // --------------- YOU --------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 1680, y: 0 },
        category: "you",
        description: "You are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 1680, y: 48 },
        category: "you",
        description: "You are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 1680, y: 96 },
        category: "you",
        description: "You are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 1680, y: 624 },
        category: "you",
        description: "You are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 1680, y: 672 },
        category: "you",
        description: "You are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 1680, y: 720 },
        category: "you",
        description: "You are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 1680, y: 768 },
        category: "you",
        description: "You are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 1680, y: 816 },
        category: "you",
        description: "You are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 1680, y: 864 },
        category: "you",
        description: "You are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 1680, y: 912 },
        category: "you",
        description: "You are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 1680, y: 1344 },
        category: "you",
        description: "You are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 1680, y: 1444 },
        category: "you",
        description: "You are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 1680, y: 1492 },
        category: "you",
        description: "You are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 1680, 1636: 0 },
        category: "you",
        description: "You are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 1680, 1732: 0 },
        category: "you",
        description: "You are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },
];

export default MULTIPLIERS;
