const MULTIPLIERS = [
    // Image base size 48x48 px

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CURSORS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //
    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 48 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cursor",
        description: "The mouse and cursors are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- GRANDMAS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "grandma",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FARMS ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "farm",
        description: "The farms are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- MINES ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "mine",
        description: "The mines are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FACTORY ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "factory",
        description: "The factories are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- BANK ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "bank",
        description: "The banks are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- TEMPLE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "temple",
        description: "The temples are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ---------- WIZARD TOWER ----------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "wizard-tower",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- SHIPMENT ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "shipment",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ----------- ALCHEMY LAB ----------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "alchemy-lab",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- PORTAL ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "portal",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- TIME MACHINE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "time-machine",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- ANTIMATTER CONDENSER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "antimatter-condenser",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- PRISM ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "prism",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CHANCMAKER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "chancemaker",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- FRACTAL ENGINE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "fractal-engine",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- JAVASCRIPT CONSOLE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "javascript-console",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- IDLEVERSE ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "idleverse",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // ------------- CORTEX BAKER ------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "cortex-baker",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },

    // ----------------------------------- //
    // ----------------------------------- //
    // --------------- YOU --------------- //
    // ----------------------------------- //
    // ----------------------------------- //

    {
        label: "Reinforced index finger",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are twice as efficient x2.",
        quote: "prod prod",
        value: 2,
        price: 100,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Carpal tunnel prevention cream",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x3.",
        quote: "prod prod",
        value: 3,
        price: 500,
        unlocksAt: 1,
        bought: false,
    },
    {
        label: "Ambidextrous",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x4.",
        quote: "prod prod",
        value: 4,
        price: 10000,
        unlocksAt: 10,
        bought: false,
    },
    {
        label: "Thousand fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x5.",
        quote: "prod prod",
        value: 5,
        price: 100000,
        unlocksAt: 25,
        bought: false,
    },
    {
        label: "Million fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x6.",
        quote: "prod prod",
        value: 6,
        price: 10000000,
        unlocksAt: 50,
        bought: false,
    },
    {
        label: "Billion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x7.",
        quote: "prod prod",
        value: 7,
        price: 100000000,
        unlocksAt: 100,
        bought: false,
    },
    {
        label: "Trillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x8.",
        quote: "prod prod",
        value: 8,
        price: 1000000000,
        unlocksAt: 150,
        bought: false,
    },
    {
        label: "Quadrillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x9.",
        quote: "prod prod",
        value: 9,
        price: 10000000000,
        unlocksAt: 200,
        bought: false,
    },
    {
        label: "Quintillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x10.",
        quote: "prod prod",
        value: 10,
        price: 10000000000000,
        unlocksAt: 250,
        bought: false,
    },
    {
        label: "Sextillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x15.",
        quote: "prod prod",
        value: 15,
        price: 10000000000000000,
        unlocksAt: 300,
        bought: false,
    },
    {
        label: "Septillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x20.",
        quote: "prod prod",
        value: 20,
        price: 10000000000000000000,
        unlocksAt: 350,
        bought: false,
    },
    {
        label: "Octillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x50.",
        quote: "prod prod",
        value: 50,
        price: 10000000000000000000000,
        unlocksAt: 400,
        bought: false,
    },
    {
        label: "Nonillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x100.",
        quote: "prod prod",
        value: 100,
        price: 10000000000000000000000000,
        unlocksAt: 450,
        bought: false,
    },
    {
        label: "Decillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x200.",
        quote: "prod prod",
        value: 200,
        price: 10000000000000000000000000000,
        unlocksAt: 500,
        bought: false,
    },
    {
        label: "Undecillion fingers",
        imagePos: { x: 0, y: 0 },
        category: "you",
        description: "The grandmas are more efficient x500.",
        quote: "prod prod",
        value: 500,
        price: 10000000000000000000000000000000,
        unlocksAt: 550,
        bought: false,
    },
];

export default MULTIPLIERS;
